version: 2.1

jobs:
  build:
    docker:
      - image: 'openjdk:17-jdk-alpine'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: ./gradlew build sonarqube -Dskip.tests

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud